# Generated by Django 5.1 on 2024-09-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.TextField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
