# Project Settings File

# Server configuration
# Machine public ip address
# If your comment server_ip, your machine's IP will be used

#server_ip=(machine_public_ip)

# Server port, recommended define server_port on 8080

server_port=8000

# Allowed hosts
# Recommended define server_ip in allowed hosts
# Add allowed hosts here, with allowed_ip=(machine_public_ip)

allowed_ip=localhost
allowed_ip=127.0.0.1

# Email service
# Free recommend: Use Outlook, because SMTP is free, your account can locked, but just go in and check again

# SMTP link, just look for the one corresponding to the email service you are going to use

email_smtp=smtp.office365.com
email_port=587

# Email information

email_address=nuvtree@outlook.com  
email_password=PEDE-A-SENHA-QUE-EU-MANDO


